spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASS}
spring.jpa.database-platform=${JPA_DB_PLATFORM}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=${SPRING_FLYWAY_ENABLED}

api.security.token.secret=${JWT_SECRET_KEY}
api.prod.admin.secret-key=${ADMIN_PROD_API_KEY}
