spring.application.name=ecommerce

Spring config properties
spring.config.import=optional:file:.env[.properties]

DB Config
spring.datasource.url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA/Hibernate Config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.profiles.active=dev

api.security.token.secret=${JWT_SECRET_KEY}
api.admin.secret-key=${ADMIN_API_KEY:}