spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASS}
spring.jpa.database-platform=${JPA_DB_PLATFORM}
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=${SPRING_FLYWAY_ENABLED}
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

api.security.token.secret=${JWT_SECRET_KEY}
api.prod.admin.secret-key=${ADMIN_PROD_API_KEY}
